#apt-get install docker*
#systemctl start docker 
#systemctl status docker
#docker info
#docker run hello-world
#docker search ubuntu
#docker pull ubuntu
#docker run ubuntu
#docker run -it ubuntu
#apt-get update
#apt-get install mariadb-server
#docker commit -m "mariadb-server installed in ubuntu docker" -a "pankaj" container_id root/name_of_image

###################DOCKER SWARM
nano /etc/hosts
ip - dockerworker
ip - dockermanager

#useradd manager
#passwd manager
#su manager
#apt-get update
#apt-get install apt-transport-https ca-certificates curl software-properties-common -y

#curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#apt-get update
#apt-get install docker-ce
# systemctl start docker
# systemctl enable docker
# docker swarm init --advertise-addr 192.168.28.129
# docker node ls
#docker service create --name my-web1 --publish 8081:80 --replicas 2 nginx
#docker service ls
#docker service ps my-web1
#docker service scale my-web1=3

####################################DOCKER-FILE

FROM ubuntu:latest
RUN apt update -y && apt upgrade -y
RUN apt-get install -y gcc
ADD ./dockerContainer /home/dockerContainer
WORKDIR /home
RUN gcc ./dockerContainer/Program.c
CMD ["./a.out"]

/////////////
#docker build -t imagename .
#docker run --name pankaj -it imagename

#############################################
dockerfile java
FROM java:8
COPY . /var/www/java/java-docker-app
WORKDIR /var/www/java/java-docker-app
RUN javac HelloWorld.java
CMD ["java","HelloWorld"]




